/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author pauloherrera
 */
public class FmCliente extends javax.swing.JFrame {

    /**
     * Creates new form FmCliente
     */
    public FmCliente() {
        initComponents();
        limpiar();
        bloquear();
    }

    Dto.Conexion metodo = new Dto.Conexion();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValidar1 = new javax.swing.JButton();
        lblApellidos = new javax.swing.JLabel();
        lblnumcliente = new javax.swing.JLabel();
        lblfechanacimiento = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblrut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtNumCliente = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        btnValidar1.setText("Guardar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        lblApellidos.setForeground(new java.awt.Color(204, 204, 204));
        lblApellidos.setText("Apellido Paterno");
        getContentPane().add(lblApellidos);
        lblApellidos.setBounds(300, 120, 110, 16);

        lblnumcliente.setForeground(new java.awt.Color(204, 204, 204));
        lblnumcliente.setText("NºCliente");
        getContentPane().add(lblnumcliente);
        lblnumcliente.setBounds(490, 20, 70, 20);

        lblfechanacimiento.setForeground(new java.awt.Color(204, 204, 204));
        lblfechanacimiento.setText("Fecha Nacimiento");
        getContentPane().add(lblfechanacimiento);
        lblfechanacimiento.setBounds(300, 140, 120, 16);

        lbldireccion.setForeground(new java.awt.Color(204, 204, 204));
        lbldireccion.setText("Dirección");
        getContentPane().add(lbldireccion);
        lbldireccion.setBounds(300, 160, 70, 16);

        lblcorreo.setForeground(new java.awt.Color(204, 204, 204));
        lblcorreo.setText("Correo");
        getContentPane().add(lblcorreo);
        lblcorreo.setBounds(300, 200, 42, 16);

        lbltelefono.setForeground(new java.awt.Color(204, 204, 204));
        lbltelefono.setText("Teléfono");
        getContentPane().add(lbltelefono);
        lbltelefono.setBounds(300, 180, 60, 16);

        lblnombre.setForeground(new java.awt.Color(204, 204, 204));
        lblnombre.setText("Nombre");
        getContentPane().add(lblnombre);
        lblnombre.setBounds(300, 100, 60, 16);

        lblrut.setForeground(new java.awt.Color(204, 204, 204));
        lblrut.setText("Rut");
        getContentPane().add(lblrut);
        lblrut.setBounds(300, 80, 21, 16);

        txtRut.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtRut);
        txtRut.setBounds(370, 80, 110, 20);

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtNombre);
        txtNombre.setBounds(370, 100, 110, 20);

        txtApellidos.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtApellidos);
        txtApellidos.setBounds(410, 120, 150, 20);

        txtFecha.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtFecha);
        txtFecha.setBounds(410, 140, 150, 20);

        txtDireccion.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(370, 160, 190, 20);

        txtTelefono.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(370, 180, 110, 20);

        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(370, 200, 110, 20);

        txtNumCliente.setEditable(false);
        txtNumCliente.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtNumCliente);
        txtNumCliente.setBounds(560, 20, 40, 20);

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidar);
        btnValidar.setBounds(480, 80, 80, 20);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(300, 330, 80, 20);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(490, 330, 80, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 10, 30, 30);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Atras");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 45, 16);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(390, 330, 90, 20);

        lblfondo.setForeground(new java.awt.Color(255, 255, 255));
        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno-lugar-trabajo-reserva-efectos-escritorio-tabla-azul-bla-fondo_75163-97.jpg"))); // NOI18N
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, -50, 660, 500);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 240, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        int i = metodo.GuardarCliente(txtRut.getText(), txtNombre.getText(), txtApellidos.getText(), txtFecha.getText(), txtTelefono.getText(), txtDireccion.getText(), txtCorreo.getText());
        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Datos Guardados");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No Guardo");
            limpiar();
        }

        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FmMenu usuario = new FmMenu();
        usuario.setVisible(true);
        usuario.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        activar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        bloquear();
// TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmCliente().setVisible(true);
            }
        });
    }

    public void activar() {
        txtRut.setEnabled(false);
        txtNombre.setEnabled(true);
        txtApellidos.setEnabled(true);
        txtFecha.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtCorreo.setEnabled(true);
        txtNombre.grabFocus();
        btnGuardar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnLimpiar.setEnabled(true);

    }

    public void bloquear() {
        txtRut.setEnabled(true);
        txtNombre.setEnabled(false);
        txtApellidos.setEnabled(false);
        txtFecha.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtRut.grabFocus();
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnLimpiar.setEnabled(false);

    }

    public void limpiar() {
        txtRut.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtFecha.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtRut.grabFocus();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnValidar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblfechanacimiento;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnumcliente;
    private javax.swing.JLabel lblrut;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumCliente;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
