/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author adminclases
 */
public class FmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FmLogin
     */
    public FmLogin() {
        initComponents();
       limpiar();
       ImageIcon imagen1 = new ImageIcon(getClass().getResource("/imagenes/iconuser.png"));
       Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(lblusericon.getWidth(), lblusericon.getHeight(), Image.SCALE_DEFAULT));
       lblusericon.setIcon(fondo1);
       this.repaint();
    }
Dto.Conexion metodo = new Dto.Conexion();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblusericon = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtClave = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Penca");
        setPreferredSize(new java.awt.Dimension(771, 520));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(lblusericon);
        lblusericon.setBounds(310, 220, 115, 115);

        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        TxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(TxtUsuario);
        TxtUsuario.setBounds(310, 350, 140, 26);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 350, 20, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lock.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 380, 20, 30);

        TxtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClaveActionPerformed(evt);
            }
        });
        TxtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtClaveKeyReleased(evt);
            }
        });
        getContentPane().add(TxtClave);
        TxtClave.setBounds(310, 380, 140, 26);

        BtnIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnIngresar);
        BtnIngresar.setBounds(280, 430, 95, 29);

        BtnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnLimpiar.setText("Limpiar");
        BtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLimpiar);
        BtnLimpiar.setBounds(390, 430, 100, 29);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondobiblioteca.jpg"))); // NOI18N
        lblfondo.setText("jLabel1");
        getContentPane().add(lblfondo);
        lblfondo.setBounds(-10, 0, 790, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
       
        String busqueda_usuario=metodo.IniciarSesion(TxtUsuario.getText(), TxtClave.getText());
       
        if(busqueda_usuario.equals("usuario encontrado")){
        JOptionPane.showMessageDialog(this, "Bienvenido/a usuario");
        this.ingresar();
        }else if(busqueda_usuario.equals("usuario no encontrado")){
     JOptionPane.showMessageDialog(this, " Credenciales de sesion incorrectos");
     limpiar();
    }
     
        
        
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void TxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUsuarioKeyTyped

        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
                //&& (c < 'A' || c > 'Z')) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioKeyTyped

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void TxtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void BtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarActionPerformed
limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLimpiarActionPerformed

    private void TxtClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtClaveKeyReleased
  BtnIngresar.setEnabled( 
          
        TxtClave.getText().length() != 0
               
        );
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClaveKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmLogin().setVisible(true);
            }
        });
    }

    public void cerrar() {
        int option = JOptionPane.showConfirmDialog(null,
                "Esta seguro que salir de la aplicacion",
                "Confirmas Cerrar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
    
    public void ingresar(){
        FmMenu menu = new FmMenu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }
    
    public void limpiar(){
        TxtUsuario.setText("");
        TxtClave.setText(null);
        TxtUsuario.requestFocus();
        BtnIngresar.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JPasswordField TxtClave;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblusericon;
    // End of variables declaration//GEN-END:variables
}
