/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author MatyWais
 */
public class FmManLibro extends javax.swing.JFrame {

    /**
     * Creates new form FmManCliente
     */
    public FmManLibro() {
        initComponents();
        Limpiar();
        
    }
    
     Dto.Conexion metodo = new Dto.Conexion();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigoLibro = new javax.swing.JTextField();
        lblRut = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblApePaterno = new javax.swing.JLabel();
        lblApeMaterno = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btngua = new javax.swing.JButton();
        btneli = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        txtNombreLibro = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtIdioma = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(626, 440));
        setMinimumSize(new java.awt.Dimension(626, 440));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(626, 440));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        txtCodigoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoLibroActionPerformed(evt);
            }
        });
        txtCodigoLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoLibroKeyTyped(evt);
            }
        });
        jPanel1.add(txtCodigoLibro);
        txtCodigoLibro.setBounds(110, 20, 200, 20);

        lblRut.setBackground(new java.awt.Color(204, 204, 204));
        lblRut.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblRut.setForeground(new java.awt.Color(255, 255, 255));
        lblRut.setText("Codigo");
        jPanel1.add(lblRut);
        lblRut.setBounds(60, 20, 50, 16);

        lblnombre.setBackground(new java.awt.Color(204, 204, 204));
        lblnombre.setForeground(new java.awt.Color(255, 255, 255));
        lblnombre.setText("Nombre ");
        jPanel1.add(lblnombre);
        lblnombre.setBounds(60, 50, 58, 16);

        lblApePaterno.setBackground(new java.awt.Color(204, 204, 204));
        lblApePaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApePaterno.setText("Editorial");
        jPanel1.add(lblApePaterno);
        lblApePaterno.setBounds(60, 80, 52, 16);

        lblApeMaterno.setBackground(new java.awt.Color(204, 204, 204));
        lblApeMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApeMaterno.setText("Autor");
        jPanel1.add(lblApeMaterno);
        lblApeMaterno.setBounds(330, 30, 40, 16);

        lblFecha.setBackground(new java.awt.Color(204, 204, 204));
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Idioma");
        jPanel1.add(lblFecha);
        lblFecha.setBounds(330, 70, 50, 16);

        btngua.setText("Guardar");
        btngua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguaActionPerformed(evt);
            }
        });
        jPanel1.add(btngua);
        btngua.setBounds(330, 330, 80, 29);

        btneli.setText("Eliminar");
        jPanel1.add(btneli);
        btneli.setBounds(510, 330, 80, 29);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar);
        Limpiar.setBounds(420, 330, 80, 29);

        txtNombreLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreLibroKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreLibro);
        txtNombreLibro.setBounds(110, 50, 200, 20);

        txtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialActionPerformed(evt);
            }
        });
        txtEditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEditorialKeyTyped(evt);
            }
        });
        jPanel1.add(txtEditorial);
        txtEditorial.setBounds(110, 80, 200, 20);

        txtIdioma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdiomaKeyTyped(evt);
            }
        });
        jPanel1.add(txtIdioma);
        txtIdioma.setBounds(380, 70, 200, 20);

        txtAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAutorKeyTyped(evt);
            }
        });
        jPanel1.add(txtAutor);
        txtAutor.setBounds(380, 30, 200, 20);

        jScrollPane2.setBackground(new java.awt.Color(0, 152, 210));

        jTable1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Editorial", "Autor", "Idioma"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 130, 590, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 50, 640, 370);

        jPanel2.setBackground(new java.awt.Color(0, 152, 210));
        jPanel2.setLayout(null);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver);
        btnVolver.setBounds(0, 0, 48, 44);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO LIBROS ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(220, 10, 230, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 630, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLibroActionPerformed

    private void txtCodigoLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoLibroKeyTyped
        char c =evt.getKeyChar();
        if(c<'0'|| c>'9')evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoLibroKeyTyped

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
Limpiar();
bloquear();
        // TODO add your handling code here:
    }//GEN-LAST:event_LimpiarActionPerformed

    private void txtNombreLibroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreLibroKeyTyped
        char c =evt.getKeyChar();
        if((c<'a'|| c>'z') && (c<'A'|| c>'Z'))evt.consume();
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLibroKeyTyped

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        FmMenu usuario = new FmMenu();
        usuario.setVisible(true);
        usuario.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtEditorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditorialKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialKeyTyped

    private void txtIdiomaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdiomaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdiomaKeyTyped

    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActionPerformed

    private void txtAutorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorKeyTyped

    private void btnguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguaActionPerformed
         int i = metodo.GuardarLibro(txtCodigoLibro.getText(), txtNombreLibro.getText(), txtEditorial.getText(), txtAutor.getText(), txtIdioma.getText());
        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Datos Guardados");
            Limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No Guardo");
            Limpiar();
        }
    }//GEN-LAST:event_btnguaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmManLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmManLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmManLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmManLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmManLibro().setVisible(true);
            }
        });
    }
    
    
public void Limpiar(){
txtNombreLibro.setText("");
txtEditorial.setText("");
txtAutor.setText("");
txtIdioma.setText("");
txtCodigoLibro.setText("");
txtCodigoLibro.grabFocus();
}
public void Activar(){
txtNombreLibro.setEnabled(true);
txtAutor.setEnabled(true);
txtEditorial.setEnabled(true);
txtIdioma.setEnabled(true);
btngua.setEnabled(true);
btneli.setEnabled(true);
txtCodigoLibro.setEnabled(false);
txtNombreLibro.grabFocus();
}
public void bloquear(){
txtNombreLibro.setEnabled(false);
txtAutor.setEnabled(false);
txtEditorial.setEnabled(false);
txtIdioma.setEnabled(false);
btngua.setEnabled(false);
btneli.setEnabled(false);
txtCodigoLibro.setEnabled(true);}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btneli;
    private javax.swing.JButton btngua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApeMaterno;
    private javax.swing.JLabel lblApePaterno;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCodigoLibro;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtIdioma;
    private javax.swing.JTextField txtNombreLibro;
    // End of variables declaration//GEN-END:variables
}
