/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author MatyWais
 */
public class FmManUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FmManUsuario
     */
    public FmManUsuario() {
        initComponents();
        limpiar();
        bloquear();
    }
    Dto.Conexion metodo = new Dto.Conexion();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lbl_ape_patern = new javax.swing.JLabel();
        lbl_ape_mater = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNacimiento = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        idusuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        cbxTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mantenedor Usuario");
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        lblRut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRut.setForeground(new java.awt.Color(204, 204, 204));
        lblRut.setText("Rut");
        getContentPane().add(lblRut);
        lblRut.setBounds(230, 40, 30, 20);

        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Nombre ");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(210, 70, 54, 16);

        lbl_ape_patern.setForeground(new java.awt.Color(204, 204, 204));
        lbl_ape_patern.setText("Apellido ");
        getContentPane().add(lbl_ape_patern);
        lbl_ape_patern.setBounds(380, 70, 70, 20);

        lbl_ape_mater.setForeground(new java.awt.Color(204, 204, 204));
        lbl_ape_mater.setText("F.Nacim");
        getContentPane().add(lbl_ape_mater);
        lbl_ape_mater.setBounds(210, 100, 60, 20);

        lbl_fecha.setForeground(new java.awt.Color(204, 204, 204));
        lbl_fecha.setText("Telefono");
        getContentPane().add(lbl_fecha);
        lbl_fecha.setBounds(380, 100, 60, 20);

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutKeyTyped(evt);
            }
        });
        getContentPane().add(txtRut);
        txtRut.setBounds(270, 40, 310, 26);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(270, 70, 110, 26);

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidos);
        txtApellidos.setBounds(440, 70, 140, 26);

        txtNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacimientoActionPerformed(evt);
            }
        });
        txtNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacimientoKeyTyped(evt);
            }
        });
        getContentPane().add(txtNacimiento);
        txtNacimiento.setBounds(270, 100, 110, 26);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(270, 130, 310, 26);

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(440, 100, 140, 26);
        getContentPane().add(txtClave);
        txtClave.setBounds(270, 160, 110, 26);

        idusuario.setEditable(false);
        getContentPane().add(idusuario);
        idusuario.setBounds(540, 10, 40, 26);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(290, 330, 93, 29);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(390, 330, 91, 29);

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(490, 330, 95, 29);

        lblid.setForeground(new java.awt.Color(204, 204, 204));
        lblid.setText("Nº");
        getContentPane().add(lblid);
        lblid.setBounds(520, 0, 30, 40);

        lblDireccion.setForeground(new java.awt.Color(204, 204, 204));
        lblDireccion.setText("Clave");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(220, 160, 40, 20);

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Direccion");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(200, 130, 60, 20);

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back.png"))); // NOI18N
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver);
        btn_volver.setBounds(10, 10, 30, 30);

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Administrador" }));
        getContentPane().add(cbxTipo);
        cbxTipo.setBounds(436, 160, 150, 27);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText(" Tipo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 160, 50, 30);

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno-lugar-trabajo-reserva-efectos-escritorio-tabla-azul-bla-fondo_75163-97.jpg"))); // NOI18N
        jLabel10.setText("asdasda");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 681, 417);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtRutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutKeyTyped

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        FmMenu usuario = new FmMenu();
        usuario.setVisible(true);
        usuario.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txtNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacimientoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoKeyTyped

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacimientoActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
        bloquear();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int i = metodo.Guardar(txtRut.getText(), txtNombre.getText(), txtApellidos.getText(), txtNacimiento.getText(), txtTelefono.getText(), txtDireccion.getText(), txtClave.getText(), (String)cbxTipo.getSelectedItem());
        if (i > 0) {
            JOptionPane.showMessageDialog(this, "Datos Guardados");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No Guardo");
            limpiar();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmManUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmManUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmManUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmManUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmManUsuario().setVisible(true);
            }
        });
    }

    public void activar() {
        txtRut.setEnabled(false);
        txtNombre.setEnabled(true);
        txtApellidos.setEnabled(true);
        txtNacimiento.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtClave.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtNombre.grabFocus();
        btnGuardar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnLimpiar.setEnabled(true);

    }

    public void bloquear() {
        txtRut.setEnabled(true);
        txtNombre.setEnabled(false);
        txtApellidos.setEnabled(false);
        txtNacimiento.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtClave.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtRut.grabFocus();
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnLimpiar.setEnabled(false);

    }

    public void limpiar() {
        txtRut.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtNacimiento.setText("");
        txtTelefono.setText("");
        txtClave.setText("");
        txtDireccion.setText("");
        btnLimpiar.setEnabled(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JTextField idusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lbl_ape_mater;
    private javax.swing.JLabel lbl_ape_patern;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
