/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;

import java.awt.Color;

/**
 *
 * @author adminclases
 */
public class FmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FmMenu
     */
    public FmMenu() {
        initComponents();
        jPanel1.setBackground(new Color(0, 0, 0, 20));
        jPanel3.setBackground(new Color(0, 0, 0, 20));
    }
    
    Dto.Conexion metodo = new Dto.Conexion();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProveedores = new javax.swing.JButton();
        btnArriendos1 = new javax.swing.JButton();
        btnClientes1 = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnLibros = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnAutores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Sistema Biblioteca");
        setPreferredSize(new java.awt.Dimension(960, 578));
        setResizable(false);
        getContentPane().setLayout(null);

        btnProveedores.setBackground(new java.awt.Color(204, 204, 204));
        btnProveedores.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-in_transit.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorderPainted(false);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedores);
        btnProveedores.setBounds(0, 400, 180, 80);

        btnArriendos1.setBackground(new java.awt.Color(204, 204, 204));
        btnArriendos1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnArriendos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-shopping_cart_2.png"))); // NOI18N
        btnArriendos1.setText("Arriendo");
        btnArriendos1.setBorderPainted(false);
        btnArriendos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArriendos1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnArriendos1);
        btnArriendos1.setBounds(0, 0, 150, 80);

        btnClientes1.setBackground(new java.awt.Color(204, 204, 204));
        btnClientes1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-groups.png"))); // NOI18N
        btnClientes1.setText("Cientes");
        btnClientes1.setBorderPainted(false);
        btnClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientes1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes1);
        btnClientes1.setBounds(0, 80, 140, 80);

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-circled_left.png"))); // NOI18N
        btnLogin.setText("Volver");
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(340, 470, 150, 80);

        btnLibros.setBackground(new java.awt.Color(204, 204, 204));
        btnLibros.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-book_stack.png"))); // NOI18N
        btnLibros.setText("Libros");
        btnLibros.setBorderPainted(false);
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        getContentPane().add(btnLibros);
        btnLibros.setBounds(0, 320, 130, 80);

        btnUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        btnUsuarios.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-add_user_male.png"))); // NOI18N
        btnUsuarios.setText("Usurios");
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuarios);
        btnUsuarios.setBounds(0, 160, 140, 80);

        btnReportes.setBackground(new java.awt.Color(204, 204, 204));
        btnReportes.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-business_report.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorderPainted(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes);
        btnReportes.setBounds(0, 480, 150, 80);

        btnAutores.setBackground(new java.awt.Color(204, 204, 204));
        btnAutores.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-check_book.png"))); // NOI18N
        btnAutores.setText("Autores");
        btnAutores.setBorderPainted(false);
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutores);
        btnAutores.setBounds(0, 240, 140, 80);

        jPanel3.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Snell Roundhand", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido a Biblioteca ");
        jLabel1.setMaximumSize(new java.awt.Dimension(757, 476));
        jLabel1.setMinimumSize(new java.awt.Dimension(757, 476));
        jLabel1.setPreferredSize(new java.awt.Dimension(757, 476));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 110);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 50, 500, 110);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 170, 580);

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondologin2.jpg"))); // NOI18N
        lblfondo.setText("jLabel4");
        getContentPane().add(lblfondo);
        lblfondo.setBounds(0, 0, 960, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        FmCliente cliente = new FmCliente();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);

// TODO add your handling code here:
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnArriendos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArriendos1ActionPerformed
        FmArriendo cliente = new FmArriendo();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnArriendos1ActionPerformed

    private void btnClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientes1ActionPerformed
        FmCliente cliente = new FmCliente();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnClientes1ActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        FmManLibro libro = new FmManLibro();
        libro.setVisible(true);
        libro.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        FmManUsuario usuario = new FmManUsuario();
        usuario.setVisible(true);
        usuario.setLocationRelativeTo(null);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        FmLogin login = new FmLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        FmManAutor autor = new FmManAutor();
        autor.setVisible(true);
        autor.setLocationRelativeTo(null);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        FmLogin login = new FmLogin();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArriendos1;
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnClientes1;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
